### ISSUE TITLE
"call_home_proxy_config" API throws error

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsc_apis#14]
Code-base: Latest from github
Python version: 2.7.12

**Observation:**
_Run the following code -_
`call_home_proxy_config(handle=handle, url='http://10.10.10.10', port='500')`

_The following error is displayed -_
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_UcsCentral\Nosetests\admin\test_callhome.py", line 63, in test_call_home_proxy_config
    port='500')
  File "c:\python27\lib\site-packages\ucsc_apis-0.9.0.0-py2.7.egg\ucsc_apis\admin\callhome.py", line 188, in call_home_proxy_config
    "call home proxy is not available.")
UcscOperationError: call_home_proxy_config failed, error: call home proxy is not available.
```

**Comment by parag-may4** [comment]
Fixed issue by https://github.com/CiscoUcs/ucsc_apis/pull/15

**Comment by tanmayx** [comment]
Verified this issue on the latest code. Works fine now.
