### ISSUE TITLE
Some apis name need refactoring

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/ucsc_apis#5]
**ucsc apis:** Latest code
**python version:** 2.7.12

**Below APIs name need to be changed in parity with others -** 
_user_add_role()_ --> should be _user_role_add()_
_user_remove_role()_ --> should be _user_role_remove()_
_user_add_locale()_ --> should be _user_locale_add()_
_user_remove_locale()_ --> should be _user_locale_remove()_

**Some more APIs to be refactored -** 
_qos_policy_add() -> qos_policy_create()_
_qos_policy_remove() -> qos_policy_delete()_
_mac_pool_remove() -> mac_pool_delete()_
_lcp_vnic_delete() -> lcp_vnic_remove()_
_lcp_iscsi_vnic_delete() -> lcp_iscsi_vnic_remove()_
_ip_pool_remove() -> ip_pool_delete()_
_radius_provider_group_add_provider() -> radius_provider_group_provider_add()_
_radius_provider_group_modify_provider() -> radius_provider_group_provider_modify()_
_radius_provider_group_remove_provider() -> radius_provider_group_provider_remove()_

Some APIs in **_tacacsplus.py_** module also needs refactoring.
**_ntp_server_create_** API name can be changed to **_ntp_server_add_**

The **_'severity'_** param in **_syslog_local_console_enable_** API takes only 3 values ('emergencies', 'alerts' and 'critical'). But as per UI, we have 5 more values ('error', 'warning', 'notification', 'information', 'debug'). Setting one of these values through the API throws below error - 

**_Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Tanmay\PythonSDK\pysdkframework\TestSuite_UcsCentral\Nosetests\admin\test_syslog.py", line 38, in test_syslog_local_console_enable_
    severity='error')
  File "c:\python27\lib\site-packages\ucsc_apis-0.9.0.0-py2.7.egg\ucsc_apis\admin\syslog.py", line 52, in syslog_local_console_enable
    mo.severity = severity
  File "c:\python27\lib\site-packages\ucscsdk-0.9.0.0-py2.7.egg\ucscsdk\ucscmo.py", line 134, in __setattr__
    self.__set_prop(name, value)
  File "c:\python27\lib\site-packages\ucscsdk-0.9.0.0-py2.7.egg\ucscsdk\ucscmo.py", line 185, in __set_prop
    value))
ValueError: Invalid Value Exception - [CommSyslogConsole]: Prop <severity>, Value<error>.
-------------------- >> begin captured logging << --------------------
ucscentral: DEBUG: severity valid values are ['alerts', 'critical', 'emergencies']
--------------------- >> end captured logging << ---------------------_**

**Comment by parag-may4** [comment]
Partially fixed this by: https://github.com/CiscoUcs/ucsc_apis/pull/10
- Fixed user related apis renaming.
- Fixed ntp api renaming.
- Fixed tacacsplus api renaming.
-> The fix to include other severity levels in syslog_local_console_enable() will be done in separate PR. It requires schema changes.

**Comment by parag-may4** [comment]
Some more APIs in ldap and locale has been fixed by: https://github.com/CiscoUcs/ucsc_apis/pull/13
